#
#  Makefile for the Linux Controller Area Network core.
#

obj-$(CONFIG_ARINC429)		+= arinc429.o
arinc429-y			:= af_arinc429.o proc.o

obj-$(CONFIG_ARINC429_RAW)	+= arinc429-raw.o
arinc429-raw-y			:= raw.o
