ccflags-y 	:= -I$(src)/include
ccflags-y	+= -D__CHECK_ENDIAN__

obj-m		+= avionics.o
avionics-y	:= net/avionics.o net/protocol.o net/protocol-raw.o net/socket-list.o

obj-m		+= vavionics.o
vavionics-y	:= devices/vavionics.o

