ccflags-y 	:= -I$(src)/include
ccflags-y	+= -D__CHECK_ENDIAN__

obj-m		+= avionics.o
avionics-y	:= net/avionics.o net/protocol.o net/protocol-raw.o net/socket-list.o net/device.o

obj-m		+= avionics-lb.o
avionics-lb-y	:= devices/lb.o

obj-m		+= avionics-example.o
avionics-example-y	:= devices/example.o
